# Data
path: C:/Users/thoma/Documents/GitHub/WING_YOLO/dataset_2 # path to your project folder
train: images/train # training images (relative to 'path')
val: images/val # validation images (relative to 'path')
#test: # test images (optional) (relative to 'path')

nc: 3 # Number of classes

# Classes
names:
  0: Solar
  1: Roof
  2: Pool